name: Docker Image CI

on:
    push:
        branches: [ master ]
        tags:
            - v*
        paths-ignore:
            - '.infra/*'

jobs:
    build-images:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout Code

            - name: Create Docker Tag
              id: docker-tag
              run : |
                  TAG=`echo ${{github.ref}} | awk 'BEGIN { FS = "/" } ; { print $3 }'`
                  LATEST_TAG="git tag --sort=-v:refname | head -n1"
                  echo $LATEST_TAG
                  echo "::set-output name=tag::$TAG"
                  echo "::set-output name=latest_tag::$LATEST_TAG"

            - name: Output Container
              run: |
                  echo ${{ steps.docker-tag.outputs.tag }}
                  echo ${{ steps.docker-tag.outputs.latest_tag }}
