name: Docker Image CI

on:
    push:
        branches: [ master ]
        paths-ignore:
            - '.infra/*'

jobs:
    build-images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                container: [cake, cron, node]
        steps:
            - uses: actions/checkout@v2
              name: Checkout Code

            - name: Create Docker Tag
              id: docker-tag
              run : |
                  TAG=`echo ${{github.ref}} | awk 'BEGIN { FS = "/" } ; { print $3 }'`
                  echo "::set-output name=tag::$TAG"

            - name: Output Container
              run: |
                  echo ${{ steps.docker-tag.outputs.tag }}